services:
  localstack:
    image: localstack/localstack:3.0.0
    container_name: zinema-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./localstack-data:/var/lib/localstack"