services:
  - type: web
    name: zinema-backend
    runtime: java
    rootDir: movie-booking/backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar --spring.profiles.active=prod
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false