aws:
  region: us-east-1
  endpoint: ""
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  dynamodb:
    movies-table: zinema-movies
    showtimes-table: zinema-showtimes
    bookings-table: zinema-bookings
  s3:
    bucket-name: zinema-posters

auth0:
  domain: dev-58r52o8fx5djc8od.us.auth0.com
  audience: https://zinema-api

stripe:
  secret-key: ${STRIPE_SECRET_KEY}

tmdb:
  api-key: ${TMDB_API_KEY}
  movie-count: 15

server:
  port: ${PORT:8080}